#!/usr/bin/env python3
"""Flag dangerous Kubernetes RBAC from manifests, before the cluster exists.

KubiScan is the authoritative check, it runs against a live cluster and sees
the effective permissions. This is the fast pre-check: parse Role / ClusterRole
YAML and flag the verb+resource combinations that grant escalation, so you catch
them at PR time instead of after `kubectl apply`.

The two are complementary, not redundant: this runs offline in CI on the YAML;
KubiScan runs on the cluster and catches things static analysis can't (effective
bindings, aggregated roles). Agreement between them is the lab's cross-check.

Run:  python scripts/rbac_lint.py k8s/risky-rbac.yaml
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pip install pyyaml")


# Each rule: (id, human reason, predicate over a policy rule dict).
def _has(rule, key, *values):
    got = rule.get(key, []) or []
    return any(v in got for v in values) or "*" in got


DANGEROUS = [
    ("escalate", "can grant itself arbitrary permissions (escalate)",
     lambda r: _has(r, "verbs", "escalate")),
    ("bind", "can bind any role to itself, including cluster-admin (bind)",
     lambda r: _has(r, "verbs", "bind")),
    ("impersonate", "can act as any user/group/SA (impersonate)",
     lambda r: _has(r, "verbs", "impersonate")),
    ("secrets-read", "can read secrets cluster-wide",
     lambda r: _has(r, "resources", "secrets")
     and _has(r, "verbs", "get", "list", "watch")),
    ("pods-create", "can create pods (schedule a pod with a privileged token)",
     lambda r: _has(r, "resources", "pods")
     and _has(r, "verbs", "create")),
    ("wildcard-all", "wildcard verb on wildcard resource (cluster-admin-equivalent)",
     lambda r: _has(r, "verbs", "*") and _has(r, "resources", "*")),
    ("token-create", "can mint service-account tokens",
     lambda r: _has(r, "resources", "serviceaccounts/token")
     and _has(r, "verbs", "create")),
]


def analyze_rule(rule):
    """Return the ids of every danger a single policy rule triggers."""
    return [rid for rid, _reason, pred in DANGEROUS if pred(rule)]


def analyze_doc(doc):
    """Return findings for one RBAC object, descending into List wrappers.

    The List handling is not a nicety. `kubectl get clusterroles,roles -A -o json`
    returns a single document of kind "List" with everything under items[], and
    an earlier version of this function checked the top-level kind and returned
    [] for anything that was not Role or ClusterRole.

    The result: pointed at a live cluster export containing four deliberately
    cluster-admin-equivalent roles, it printed "No risky RBAC found" and exited
    0. A clean report generated by reading nothing, which is the most dangerous
    output a security tool can produce. Verified against a real kind cluster,
    84 objects in, zero findings out.

    kubectl also emits typed list kinds (RoleList, ClusterRoleList) depending on
    how it is invoked, so match any *List with an items array rather than the
    single literal "List".
    """
    if not doc:
        return []

    kind = doc.get("kind", "")
    if kind.endswith("List") and isinstance(doc.get("items"), list):
        findings = []
        for item in doc["items"]:
            findings.extend(analyze_doc(item))
        return findings

    if kind not in ("Role", "ClusterRole"):
        return []

    meta = doc.get("metadata", {}) or {}
    name = meta.get("name", "?")

    # Kubernetes stamps every role it ships with
    # kubernetes.io/bootstrapping: rbac-defaults. cluster-admin genuinely can
    # escalate, bind and impersonate, and reporting that as a finding is
    # technically true and operationally useless.
    #
    # Against a real cluster this is the difference between a report someone
    # reads and one they close: 62 findings, of which 51 were the roles
    # Kubernetes installed itself and 11 were the deliberately planted ones.
    # Burying the 11 in the 62 is its own kind of failure.
    #
    # Classified, not suppressed. Built-ins stay in the output and stay
    # counted, they are just not what the exit code is about.
    labels = meta.get("labels", {}) or {}
    builtin = labels.get("kubernetes.io/bootstrapping") == "rbac-defaults"

    findings = []
    for rule in doc.get("rules", []) or []:
        for rid in analyze_rule(rule):
            reason = next(r for i, r, _ in DANGEROUS if i == rid)
            findings.append({
                "kind": kind,
                "name": name,
                "risk": rid,
                "reason": reason,
                "builtin": builtin,
            })
    return findings


def analyze_text(text):
    """Findings across a multi-doc YAML string."""
    findings = []
    for doc in yaml.safe_load_all(text):
        findings.extend(analyze_doc(doc))
    return findings


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    show_builtin = "--include-builtin" in sys.argv

    if not args:
        sys.exit(
            "usage: rbac_lint.py [--include-builtin] <manifest.yaml|cluster.json> ...\n"
            "\n"
            "Accepts manifests or a live export:\n"
            "  kubectl get clusterroles,roles -A -o json > rbac.json\n"
            "  python scripts/rbac_lint.py rbac.json"
        )

    total = []
    for path in args:
        p = Path(path)
        if not p.exists():
            # Never let a missing input read as a clean scan.
            sys.exit(f"error: {path} does not exist")
        findings = analyze_text(p.read_text(encoding="utf-8-sig"))
        total.extend(findings)

    custom = [f for f in total if not f["builtin"]]
    builtin = [f for f in total if f["builtin"]]

    for f in custom:
        print(f"  [{f['risk']:14}] {f['kind']}/{f['name']}: {f['reason']}")

    if builtin:
        if show_builtin:
            print()
            print("  --- Kubernetes built-ins (kubernetes.io/bootstrapping: rbac-defaults) ---")
            for f in builtin:
                print(f"  [{f['risk']:14}] {f['kind']}/{f['name']}: {f['reason']}")
        else:
            print()
            print(f"  ({len(builtin)} finding(s) on Kubernetes built-in roles hidden, "
                  f"--include-builtin to show)")

    print()
    if custom:
        print(f"{len(custom)} risky RBAC rule(s) found on non-built-in roles.")
        print("Confirm each against KubiScan's live-cluster output, they should agree.")
        sys.exit(1)
    print("No risky RBAC found outside Kubernetes' own defaults.")


if __name__ == "__main__":
    main()
